/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestIframeRouteImport } from './routes/test-iframe'
import { Route as StaffSignInRouteImport } from './routes/staff-sign-in'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer/index'
import { Route as MyTicketsIndexRouteImport } from './routes/my-tickets/index'
import { Route as StaffScanSuccessRouteImport } from './routes/staff/scan-success'
import { Route as StaffScanRouteImport } from './routes/staff/scan'
import { Route as OrganizerCreateRouteImport } from './routes/organizer/create'
import { Route as MyTicketsTicketIdRouteImport } from './routes/my-tickets/$ticketId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as MyTicketsTicketIdIndexRouteImport } from './routes/my-tickets/$ticketId/index'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as OrganizerEventsEventIdRouteImport } from './routes/organizer/events/$eventId'
import { Route as OrganizerEditEventIdRouteImport } from './routes/organizer/edit/$eventId'
import { Route as MyTicketsTicketIdQrRouteImport } from './routes/my-tickets/$ticketId/qr'
import { Route as EventsEventIdPurchaseRouteImport } from './routes/events/$eventId/purchase'
import { Route as EventsEventIdChooseRouteImport } from './routes/events/$eventId/choose'

const TestIframeRoute = TestIframeRouteImport.update({
  id: '/test-iframe',
  path: '/test-iframe',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSignInRoute = StaffSignInRouteImport.update({
  id: '/staff-sign-in',
  path: '/staff-sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRoute,
} as any)
const MyTicketsIndexRoute = MyTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyTicketsRoute,
} as any)
const StaffScanSuccessRoute = StaffScanSuccessRouteImport.update({
  id: '/scan-success',
  path: '/scan-success',
  getParentRoute: () => StaffRoute,
} as any)
const StaffScanRoute = StaffScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => StaffRoute,
} as any)
const OrganizerCreateRoute = OrganizerCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OrganizerRoute,
} as any)
const MyTicketsTicketIdRoute = MyTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => MyTicketsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsTicketIdIndexRoute = MyTicketsTicketIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyTicketsTicketIdRoute,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const OrganizerEventsEventIdRoute = OrganizerEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerEditEventIdRoute = OrganizerEditEventIdRouteImport.update({
  id: '/edit/$eventId',
  path: '/edit/$eventId',
  getParentRoute: () => OrganizerRoute,
} as any)
const MyTicketsTicketIdQrRoute = MyTicketsTicketIdQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => MyTicketsTicketIdRoute,
} as any)
const EventsEventIdPurchaseRoute = EventsEventIdPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdChooseRoute = EventsEventIdChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => EventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-tickets': typeof MyTicketsRouteWithChildren
  '/organizer': typeof OrganizerRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/sign-in': typeof SignInRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff-sign-in': typeof StaffSignInRoute
  '/test-iframe': typeof TestIframeRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/my-tickets/$ticketId': typeof MyTicketsTicketIdRouteWithChildren
  '/organizer/create': typeof OrganizerCreateRoute
  '/staff/scan': typeof StaffScanRoute
  '/staff/scan-success': typeof StaffScanSuccessRoute
  '/my-tickets/': typeof MyTicketsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/events/$eventId/choose': typeof EventsEventIdChooseRoute
  '/events/$eventId/purchase': typeof EventsEventIdPurchaseRoute
  '/my-tickets/$ticketId/qr': typeof MyTicketsTicketIdQrRoute
  '/organizer/edit/$eventId': typeof OrganizerEditEventIdRoute
  '/organizer/events/$eventId': typeof OrganizerEventsEventIdRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/my-tickets/$ticketId/': typeof MyTicketsTicketIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/showcase': typeof ShowcaseRoute
  '/sign-in': typeof SignInRoute
  '/staff-sign-in': typeof StaffSignInRoute
  '/test-iframe': typeof TestIframeRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/staff/scan': typeof StaffScanRoute
  '/staff/scan-success': typeof StaffScanSuccessRoute
  '/my-tickets': typeof MyTicketsIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/staff': typeof StaffIndexRoute
  '/events/$eventId/choose': typeof EventsEventIdChooseRoute
  '/events/$eventId/purchase': typeof EventsEventIdPurchaseRoute
  '/my-tickets/$ticketId/qr': typeof MyTicketsTicketIdQrRoute
  '/organizer/edit/$eventId': typeof OrganizerEditEventIdRoute
  '/organizer/events/$eventId': typeof OrganizerEventsEventIdRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/my-tickets/$ticketId': typeof MyTicketsTicketIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-tickets': typeof MyTicketsRouteWithChildren
  '/organizer': typeof OrganizerRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/sign-in': typeof SignInRoute
  '/staff': typeof StaffRouteWithChildren
  '/staff-sign-in': typeof StaffSignInRoute
  '/test-iframe': typeof TestIframeRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/my-tickets/$ticketId': typeof MyTicketsTicketIdRouteWithChildren
  '/organizer/create': typeof OrganizerCreateRoute
  '/staff/scan': typeof StaffScanRoute
  '/staff/scan-success': typeof StaffScanSuccessRoute
  '/my-tickets/': typeof MyTicketsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/events/$eventId/choose': typeof EventsEventIdChooseRoute
  '/events/$eventId/purchase': typeof EventsEventIdPurchaseRoute
  '/my-tickets/$ticketId/qr': typeof MyTicketsTicketIdQrRoute
  '/organizer/edit/$eventId': typeof OrganizerEditEventIdRoute
  '/organizer/events/$eventId': typeof OrganizerEventsEventIdRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/my-tickets/$ticketId/': typeof MyTicketsTicketIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-tickets'
    | '/organizer'
    | '/showcase'
    | '/sign-in'
    | '/staff'
    | '/staff-sign-in'
    | '/test-iframe'
    | '/events/$eventId'
    | '/my-tickets/$ticketId'
    | '/organizer/create'
    | '/staff/scan'
    | '/staff/scan-success'
    | '/my-tickets/'
    | '/organizer/'
    | '/profile/'
    | '/staff/'
    | '/events/$eventId/choose'
    | '/events/$eventId/purchase'
    | '/my-tickets/$ticketId/qr'
    | '/organizer/edit/$eventId'
    | '/organizer/events/$eventId'
    | '/events/$eventId/'
    | '/my-tickets/$ticketId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/showcase'
    | '/sign-in'
    | '/staff-sign-in'
    | '/test-iframe'
    | '/organizer/create'
    | '/staff/scan'
    | '/staff/scan-success'
    | '/my-tickets'
    | '/organizer'
    | '/profile'
    | '/staff'
    | '/events/$eventId/choose'
    | '/events/$eventId/purchase'
    | '/my-tickets/$ticketId/qr'
    | '/organizer/edit/$eventId'
    | '/organizer/events/$eventId'
    | '/events/$eventId'
    | '/my-tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/my-tickets'
    | '/organizer'
    | '/showcase'
    | '/sign-in'
    | '/staff'
    | '/staff-sign-in'
    | '/test-iframe'
    | '/events/$eventId'
    | '/my-tickets/$ticketId'
    | '/organizer/create'
    | '/staff/scan'
    | '/staff/scan-success'
    | '/my-tickets/'
    | '/organizer/'
    | '/profile/'
    | '/staff/'
    | '/events/$eventId/choose'
    | '/events/$eventId/purchase'
    | '/my-tickets/$ticketId/qr'
    | '/organizer/edit/$eventId'
    | '/organizer/events/$eventId'
    | '/events/$eventId/'
    | '/my-tickets/$ticketId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyTicketsRoute: typeof MyTicketsRouteWithChildren
  OrganizerRoute: typeof OrganizerRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRoute
  SignInRoute: typeof SignInRoute
  StaffRoute: typeof StaffRouteWithChildren
  StaffSignInRoute: typeof StaffSignInRoute
  TestIframeRoute: typeof TestIframeRoute
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-iframe': {
      id: '/test-iframe'
      path: '/test-iframe'
      fullPath: '/test-iframe'
      preLoaderRoute: typeof TestIframeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-sign-in': {
      id: '/staff-sign-in'
      path: '/staff-sign-in'
      fullPath: '/staff-sign-in'
      preLoaderRoute: typeof StaffSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof StaffRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/my-tickets/': {
      id: '/my-tickets/'
      path: '/'
      fullPath: '/my-tickets/'
      preLoaderRoute: typeof MyTicketsIndexRouteImport
      parentRoute: typeof MyTicketsRoute
    }
    '/staff/scan-success': {
      id: '/staff/scan-success'
      path: '/scan-success'
      fullPath: '/staff/scan-success'
      preLoaderRoute: typeof StaffScanSuccessRouteImport
      parentRoute: typeof StaffRoute
    }
    '/staff/scan': {
      id: '/staff/scan'
      path: '/scan'
      fullPath: '/staff/scan'
      preLoaderRoute: typeof StaffScanRouteImport
      parentRoute: typeof StaffRoute
    }
    '/organizer/create': {
      id: '/organizer/create'
      path: '/create'
      fullPath: '/organizer/create'
      preLoaderRoute: typeof OrganizerCreateRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/my-tickets/$ticketId': {
      id: '/my-tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/my-tickets/$ticketId'
      preLoaderRoute: typeof MyTicketsTicketIdRouteImport
      parentRoute: typeof MyTicketsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets/$ticketId/': {
      id: '/my-tickets/$ticketId/'
      path: '/'
      fullPath: '/my-tickets/$ticketId/'
      preLoaderRoute: typeof MyTicketsTicketIdIndexRouteImport
      parentRoute: typeof MyTicketsTicketIdRoute
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/organizer/events/$eventId': {
      id: '/organizer/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/organizer/events/$eventId'
      preLoaderRoute: typeof OrganizerEventsEventIdRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/edit/$eventId': {
      id: '/organizer/edit/$eventId'
      path: '/edit/$eventId'
      fullPath: '/organizer/edit/$eventId'
      preLoaderRoute: typeof OrganizerEditEventIdRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/my-tickets/$ticketId/qr': {
      id: '/my-tickets/$ticketId/qr'
      path: '/qr'
      fullPath: '/my-tickets/$ticketId/qr'
      preLoaderRoute: typeof MyTicketsTicketIdQrRouteImport
      parentRoute: typeof MyTicketsTicketIdRoute
    }
    '/events/$eventId/purchase': {
      id: '/events/$eventId/purchase'
      path: '/purchase'
      fullPath: '/events/$eventId/purchase'
      preLoaderRoute: typeof EventsEventIdPurchaseRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/choose': {
      id: '/events/$eventId/choose'
      path: '/choose'
      fullPath: '/events/$eventId/choose'
      preLoaderRoute: typeof EventsEventIdChooseRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
  }
}

interface MyTicketsTicketIdRouteChildren {
  MyTicketsTicketIdQrRoute: typeof MyTicketsTicketIdQrRoute
  MyTicketsTicketIdIndexRoute: typeof MyTicketsTicketIdIndexRoute
}

const MyTicketsTicketIdRouteChildren: MyTicketsTicketIdRouteChildren = {
  MyTicketsTicketIdQrRoute: MyTicketsTicketIdQrRoute,
  MyTicketsTicketIdIndexRoute: MyTicketsTicketIdIndexRoute,
}

const MyTicketsTicketIdRouteWithChildren =
  MyTicketsTicketIdRoute._addFileChildren(MyTicketsTicketIdRouteChildren)

interface MyTicketsRouteChildren {
  MyTicketsTicketIdRoute: typeof MyTicketsTicketIdRouteWithChildren
  MyTicketsIndexRoute: typeof MyTicketsIndexRoute
}

const MyTicketsRouteChildren: MyTicketsRouteChildren = {
  MyTicketsTicketIdRoute: MyTicketsTicketIdRouteWithChildren,
  MyTicketsIndexRoute: MyTicketsIndexRoute,
}

const MyTicketsRouteWithChildren = MyTicketsRoute._addFileChildren(
  MyTicketsRouteChildren,
)

interface OrganizerRouteChildren {
  OrganizerCreateRoute: typeof OrganizerCreateRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  OrganizerEditEventIdRoute: typeof OrganizerEditEventIdRoute
  OrganizerEventsEventIdRoute: typeof OrganizerEventsEventIdRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerCreateRoute: OrganizerCreateRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  OrganizerEditEventIdRoute: OrganizerEditEventIdRoute,
  OrganizerEventsEventIdRoute: OrganizerEventsEventIdRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

interface StaffRouteChildren {
  StaffScanRoute: typeof StaffScanRoute
  StaffScanSuccessRoute: typeof StaffScanSuccessRoute
  StaffIndexRoute: typeof StaffIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffScanRoute: StaffScanRoute,
  StaffScanSuccessRoute: StaffScanSuccessRoute,
  StaffIndexRoute: StaffIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface EventsEventIdRouteChildren {
  EventsEventIdChooseRoute: typeof EventsEventIdChooseRoute
  EventsEventIdPurchaseRoute: typeof EventsEventIdPurchaseRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdChooseRoute: EventsEventIdChooseRoute,
  EventsEventIdPurchaseRoute: EventsEventIdPurchaseRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyTicketsRoute: MyTicketsRouteWithChildren,
  OrganizerRoute: OrganizerRouteWithChildren,
  ShowcaseRoute: ShowcaseRoute,
  SignInRoute: SignInRoute,
  StaffRoute: StaffRouteWithChildren,
  StaffSignInRoute: StaffSignInRoute,
  TestIframeRoute: TestIframeRoute,
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
