/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as MyTicketsRouteImport } from './routes/my-tickets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer/index'
import { Route as MyTicketsIndexRouteImport } from './routes/my-tickets/index'
import { Route as OrganizerCreateRouteImport } from './routes/organizer/create'
import { Route as MyTicketsTicketIdRouteImport } from './routes/my-tickets/$ticketId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as MyTicketsTicketIdIndexRouteImport } from './routes/my-tickets/$ticketId/index'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as OrganizerEventsEventIdRouteImport } from './routes/organizer/events/$eventId'
import { Route as MyTicketsTicketIdQrRouteImport } from './routes/my-tickets/$ticketId/qr'
import { Route as EventsEventIdPurchaseRouteImport } from './routes/events/$eventId/purchase'
import { Route as EventsEventIdChooseRouteImport } from './routes/events/$eventId/choose'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsRoute = MyTicketsRouteImport.update({
  id: '/my-tickets',
  path: '/my-tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRoute,
} as any)
const MyTicketsIndexRoute = MyTicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyTicketsRoute,
} as any)
const OrganizerCreateRoute = OrganizerCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => OrganizerRoute,
} as any)
const MyTicketsTicketIdRoute = MyTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => MyTicketsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTicketsTicketIdIndexRoute = MyTicketsTicketIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyTicketsTicketIdRoute,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const OrganizerEventsEventIdRoute = OrganizerEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => OrganizerRoute,
} as any)
const MyTicketsTicketIdQrRoute = MyTicketsTicketIdQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => MyTicketsTicketIdRoute,
} as any)
const EventsEventIdPurchaseRoute = EventsEventIdPurchaseRouteImport.update({
  id: '/purchase',
  path: '/purchase',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdChooseRoute = EventsEventIdChooseRouteImport.update({
  id: '/choose',
  path: '/choose',
  getParentRoute: () => EventsEventIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-tickets': typeof MyTicketsRouteWithChildren
  '/organizer': typeof OrganizerRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/sign-in': typeof SignInRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/my-tickets/$ticketId': typeof MyTicketsTicketIdRouteWithChildren
  '/organizer/create': typeof OrganizerCreateRoute
  '/my-tickets/': typeof MyTicketsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/events/$eventId/choose': typeof EventsEventIdChooseRoute
  '/events/$eventId/purchase': typeof EventsEventIdPurchaseRoute
  '/my-tickets/$ticketId/qr': typeof MyTicketsTicketIdQrRoute
  '/organizer/events/$eventId': typeof OrganizerEventsEventIdRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/my-tickets/$ticketId/': typeof MyTicketsTicketIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/showcase': typeof ShowcaseRoute
  '/sign-in': typeof SignInRoute
  '/organizer/create': typeof OrganizerCreateRoute
  '/my-tickets': typeof MyTicketsIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/events/$eventId/choose': typeof EventsEventIdChooseRoute
  '/events/$eventId/purchase': typeof EventsEventIdPurchaseRoute
  '/my-tickets/$ticketId/qr': typeof MyTicketsTicketIdQrRoute
  '/organizer/events/$eventId': typeof OrganizerEventsEventIdRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/my-tickets/$ticketId': typeof MyTicketsTicketIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-tickets': typeof MyTicketsRouteWithChildren
  '/organizer': typeof OrganizerRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/sign-in': typeof SignInRoute
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/my-tickets/$ticketId': typeof MyTicketsTicketIdRouteWithChildren
  '/organizer/create': typeof OrganizerCreateRoute
  '/my-tickets/': typeof MyTicketsIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/events/$eventId/choose': typeof EventsEventIdChooseRoute
  '/events/$eventId/purchase': typeof EventsEventIdPurchaseRoute
  '/my-tickets/$ticketId/qr': typeof MyTicketsTicketIdQrRoute
  '/organizer/events/$eventId': typeof OrganizerEventsEventIdRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/my-tickets/$ticketId/': typeof MyTicketsTicketIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/my-tickets'
    | '/organizer'
    | '/showcase'
    | '/sign-in'
    | '/events/$eventId'
    | '/my-tickets/$ticketId'
    | '/organizer/create'
    | '/my-tickets/'
    | '/organizer/'
    | '/profile/'
    | '/events/$eventId/choose'
    | '/events/$eventId/purchase'
    | '/my-tickets/$ticketId/qr'
    | '/organizer/events/$eventId'
    | '/events/$eventId/'
    | '/my-tickets/$ticketId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/showcase'
    | '/sign-in'
    | '/organizer/create'
    | '/my-tickets'
    | '/organizer'
    | '/profile'
    | '/events/$eventId/choose'
    | '/events/$eventId/purchase'
    | '/my-tickets/$ticketId/qr'
    | '/organizer/events/$eventId'
    | '/events/$eventId'
    | '/my-tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/my-tickets'
    | '/organizer'
    | '/showcase'
    | '/sign-in'
    | '/events/$eventId'
    | '/my-tickets/$ticketId'
    | '/organizer/create'
    | '/my-tickets/'
    | '/organizer/'
    | '/profile/'
    | '/events/$eventId/choose'
    | '/events/$eventId/purchase'
    | '/my-tickets/$ticketId/qr'
    | '/organizer/events/$eventId'
    | '/events/$eventId/'
    | '/my-tickets/$ticketId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyTicketsRoute: typeof MyTicketsRouteWithChildren
  OrganizerRoute: typeof OrganizerRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRoute
  SignInRoute: typeof SignInRoute
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets': {
      id: '/my-tickets'
      path: '/my-tickets'
      fullPath: '/my-tickets'
      preLoaderRoute: typeof MyTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/my-tickets/': {
      id: '/my-tickets/'
      path: '/'
      fullPath: '/my-tickets/'
      preLoaderRoute: typeof MyTicketsIndexRouteImport
      parentRoute: typeof MyTicketsRoute
    }
    '/organizer/create': {
      id: '/organizer/create'
      path: '/create'
      fullPath: '/organizer/create'
      preLoaderRoute: typeof OrganizerCreateRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/my-tickets/$ticketId': {
      id: '/my-tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/my-tickets/$ticketId'
      preLoaderRoute: typeof MyTicketsTicketIdRouteImport
      parentRoute: typeof MyTicketsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tickets/$ticketId/': {
      id: '/my-tickets/$ticketId/'
      path: '/'
      fullPath: '/my-tickets/$ticketId/'
      preLoaderRoute: typeof MyTicketsTicketIdIndexRouteImport
      parentRoute: typeof MyTicketsTicketIdRoute
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/organizer/events/$eventId': {
      id: '/organizer/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/organizer/events/$eventId'
      preLoaderRoute: typeof OrganizerEventsEventIdRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/my-tickets/$ticketId/qr': {
      id: '/my-tickets/$ticketId/qr'
      path: '/qr'
      fullPath: '/my-tickets/$ticketId/qr'
      preLoaderRoute: typeof MyTicketsTicketIdQrRouteImport
      parentRoute: typeof MyTicketsTicketIdRoute
    }
    '/events/$eventId/purchase': {
      id: '/events/$eventId/purchase'
      path: '/purchase'
      fullPath: '/events/$eventId/purchase'
      preLoaderRoute: typeof EventsEventIdPurchaseRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/choose': {
      id: '/events/$eventId/choose'
      path: '/choose'
      fullPath: '/events/$eventId/choose'
      preLoaderRoute: typeof EventsEventIdChooseRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
  }
}

interface MyTicketsTicketIdRouteChildren {
  MyTicketsTicketIdQrRoute: typeof MyTicketsTicketIdQrRoute
  MyTicketsTicketIdIndexRoute: typeof MyTicketsTicketIdIndexRoute
}

const MyTicketsTicketIdRouteChildren: MyTicketsTicketIdRouteChildren = {
  MyTicketsTicketIdQrRoute: MyTicketsTicketIdQrRoute,
  MyTicketsTicketIdIndexRoute: MyTicketsTicketIdIndexRoute,
}

const MyTicketsTicketIdRouteWithChildren =
  MyTicketsTicketIdRoute._addFileChildren(MyTicketsTicketIdRouteChildren)

interface MyTicketsRouteChildren {
  MyTicketsTicketIdRoute: typeof MyTicketsTicketIdRouteWithChildren
  MyTicketsIndexRoute: typeof MyTicketsIndexRoute
}

const MyTicketsRouteChildren: MyTicketsRouteChildren = {
  MyTicketsTicketIdRoute: MyTicketsTicketIdRouteWithChildren,
  MyTicketsIndexRoute: MyTicketsIndexRoute,
}

const MyTicketsRouteWithChildren = MyTicketsRoute._addFileChildren(
  MyTicketsRouteChildren,
)

interface OrganizerRouteChildren {
  OrganizerCreateRoute: typeof OrganizerCreateRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  OrganizerEventsEventIdRoute: typeof OrganizerEventsEventIdRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerCreateRoute: OrganizerCreateRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  OrganizerEventsEventIdRoute: OrganizerEventsEventIdRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

interface EventsEventIdRouteChildren {
  EventsEventIdChooseRoute: typeof EventsEventIdChooseRoute
  EventsEventIdPurchaseRoute: typeof EventsEventIdPurchaseRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdChooseRoute: EventsEventIdChooseRoute,
  EventsEventIdPurchaseRoute: EventsEventIdPurchaseRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyTicketsRoute: MyTicketsRouteWithChildren,
  OrganizerRoute: OrganizerRouteWithChildren,
  ShowcaseRoute: ShowcaseRoute,
  SignInRoute: SignInRoute,
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
